version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Docker Hub..."
      - echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 921167706163.dkr.ecr.eu-west-1.amazonaws.com
      - docker buildx create --use --name localbuilder
  build:
    commands:
      - echo Building Docker image using buildx local builder...
      - docker buildx build --load -t 921167706163.dkr.ecr.eu-west-1.amazonaws.com/openedgeagentmcp:Development .
  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 921167706163.dkr.ecr.eu-west-1.amazonaws.com
      - docker push 921167706163.dkr.ecr.eu-west-1.amazonaws.com/openedgeagentmcp:Development
      - echo Docker image push completed.
artifacts:
  files: []
